# Generated by Django 3.0.5 on 2020-05-07 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_auto_20200507_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.Location'),
        ),
    ]
