# Generated by Django 3.0.5 on 2020-05-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0003_auto_20200507_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='is_status_open',
            field=models.BooleanField(default=True),
        ),
    ]
