# Generated by Django 3.0.5 on 2020-05-07 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0001_initial'),
        ('reporter', '0004_incidentreport_is_status_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='responder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='responder.Responder'),
        ),
    ]
