# Generated by Django 3.0.5 on 2020-05-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0011_auto_20200508_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentlocation',
            old_name='name',
            new_name='map_name',
        ),
        migrations.AddField(
            model_name='incidentlocation',
            name='known_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
