# Generated by Django 3.0.5 on 2020-05-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0013_auto_20200519_1300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
