# Generated by Django 3.0.5 on 2020-05-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0014_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentlocation',
            name='formatted_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='incidentlocation',
            name='formatted_phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incidentlocation',
            name='international_phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incidentlocation',
            name='place_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='incidentlocation',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='incidentlocation',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incidentlocation',
            name='known_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentlocation',
            name='map_name',
            field=models.CharField(max_length=200),
        ),
    ]
