# Generated by Django 3.0.5 on 2020-05-20 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0002_responder_location'),
        ('reporter', '0015_auto_20200520_0035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IncidentLocation',
            new_name='Place',
        ),
    ]
