# Generated by Django 3.0.5 on 2020-05-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0016_auto_20200520_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='owner',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
