# Generated by Django 3.0.5 on 2020-06-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0017_place_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='is_status_open',
        ),
    ]
