# Generated by Django 3.0.5 on 2020-06-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0018_remove_incidentreport_is_status_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
