# Generated by Django 3.0.5 on 2020-05-18 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0011_auto_20200508_1357'),
        ('responder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responder',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responder', to='reporter.IncidentLocation'),
            preserve_default=False,
        ),
    ]
